### ISSUE TITLE
signature is not valid

### ISSUE THREAD

**Issue by eLenoAr** [DGG3D/webhook-api-example#1]
I've been running the provided example with a registered webhook at the RapidCompact dashboard (using ngrok).
Secrets are correctly set, but in the end, the signature is not valid.

Has something changed in the backend for the RapidCompact Rest API?

ping me for further details, if needed.

**Comment by Tiaskel** [comment]
Hey there. We will investigate the issue and get back to you.

**Comment by Tiaskel** [comment]
Hey @eLenoAr 

I have tested the solution in this repo and it still works for me using the example secret "secret" and ngrok to expose the local server to the web (see attached screenshot). Our webhook logic shouldn't have changed since last year, as far as I can tell from our codebase. 

Can you share your code and the settings you used? 

![grafik](https://github.com/DGG3D/webhook-api-example/assets/10125782/3ef99133-06f2-44c5-b65b-53b6e3e48ee2)

**Comment by eLenoAr** [comment]
Well, whatever hiccup that has been, now it works fine for me, too.

Sorry for any inconvenience caused.
